cspace-deployment/radiance

- extras/cinefiles_catalog_controller.rb
> CSW-274: Add date range widgets to facet list

- extras/cinefiles_catalog_controller.rb
- extras/cinefiles_footer.html.erb
- extras/cinefiles_splash.html.erb
Sorry there were some last minute copy edit changes requested :/
> HMP 203: copy edits to Nov 2021 cinefiles splash page

- extras/cinefiles_splash.html.erb
> HMP-203: correction to silent film stars splash page URL

- portal/app/assets/stylesheets/shared.scss
https://jira-secure.berkeley.edu/browse/HMP-307
> HMP-307: increases top nav link color contrast

- extras/pahma/app/assets/stylesheets/extras.scss
- extras/pahma/app/views/shared/_footer.html.erb
- extras/pahma/app/views/shared/_header_navbar.html.erb
- portal/app/assets/stylesheets/shared.scss
https://jira-secure.berkeley.edu/browse/HMP-317
https://jira-secure.berkeley.edu/browse/HMP-318
> HMP-317: overrides bootstrap focus ring for better visibility; HMP-318: makes masonry captions keyboard accessible

- extras/pahma/app/assets/stylesheets/extras.scss
- portal/app/assets/javascripts/blacklight_gallery.js
- portal/app/assets/stylesheets/shared.scss
https://jira-secure.berkeley.edu/browse/HMP-324
https://jira-secure.berkeley.edu/browse/HMP-325
This is hacking the blacklight-gallery slideshow component once it's loaded on the page. Is this a good idea or is there a better way?
> HMP-325: adds accessible labels in slideshow modal; HMP-324: further improves focus visibility

- portal/app/assets/stylesheets/shared.scss
https://jira-secure.berkeley.edu/browse/HMP-319
> HMP-319: prevents bookmark toggle overflow in gallery, masonry views

- extras/bampfa/app/views/shared/_header_navbar.html.erb
- extras/cinefiles/app/assets/stylesheets/extras.scss
- extras/cinefiles/app/views/shared/_header_navbar.html.erb
- extras/pahma/app/views/shared/_header_navbar.html.erb
https://jira-secure.berkeley.edu/browse/HMP-334
> HMP-334: improves nav bar responsiveness

- extras/pahma/app/assets/stylesheets/extras.scss
- extras/pahma/app/views/catalog/_home_text.html.erb
https://jira-secure.berkeley.edu/browse/HMP-320
> HMP-320: replaces pahma splash page layout table

- extras/pahma/app/assets/stylesheets/extras.scss
- extras/pahma/app/views/catalog/_home_text.html.erb
- extras/pahma/app/views/shared/_header_navbar.html.erb
https://jira-secure.berkeley.edu/browse/HMP-329
> HMP-329: fixes pahma heading structure

- extras/bampfa/app/views/catalog/_show_preview.html.erb
https://jira-secure.berkeley.edu/browse/HMP-331
> HMP-331: fixes bampfa heading structure part 2

- extras/cinefiles/app/views/devise/sessions/new.html.erb
- extras/cinefiles/app/views/shared/_pdfs.html.erb
https://jira-secure.berkeley.edu/browse/HMP-330
> HMP-330: fixes cinefiles heading structure

- extras/bampfa/app/assets/stylesheets/extras.scss
- portal/app/assets/stylesheets/shared.scss
https://jira-secure.berkeley.edu/browse/HMP-335
https://jira-secure.berkeley.edu/browse/HMP-340
https://jira-secure.berkeley.edu/browse/HMP-343
> HMP-335, HMP-340, HMP-343: fixes bampfa text resizing

- extras/bampfa/app/assets/stylesheets/extras.scss
- extras/bampfa/app/views/catalog/_document_gallery.html.erb
- portal/app/assets/stylesheets/shared.scss
https://jira-secure.berkeley.edu/browse/HMP-336
> HMP-336: prevents captions overlap when text resized

- extras/cinefiles/app/assets/stylesheets/extras.scss
- extras/cinefiles/app/assets/stylesheets/tiles.css
- extras/cinefiles/app/views/catalog/_home_text.html.erb
- extras/other/makestatic.py
- extras/pahma/app/views/catalog/_home_text.html.erb
https://jira-secure.berkeley.edu/browse/HMP-337
> HMP-337: text resize isotope items; HMP-345: left-justifies text

- extras/bampfa/app/assets/stylesheets/extras.scss
- extras/bampfa/app/views/shared/_footer.html.erb
- extras/cinefiles/app/assets/stylesheets/extras.scss
- extras/cinefiles/app/views/shared/_footer.html.erb
- extras/pahma/app/assets/stylesheets/extras.scss
- extras/pahma/app/views/shared/_footer.html.erb
- portal/app/assets/stylesheets/shared.scss
https://jira-secure.berkeley.edu/browse/HMP-333
I also moved styles that are only used by PAHMA from shared.scss to PAHMA's extras.scss.
> HMP-333, HMP-338: prevents footer col overlap when text resized

- extras/bampfa/app/views/catalog/_home_text.html.erb
- extras/bampfa/app/views/errors/internal_server_error.html.erb
- extras/bampfa/app/views/errors/not_found.html.erb
- extras/cinefiles/app/assets/stylesheets/tiles.css
- extras/cinefiles/app/views/catalog/_home_text.html.erb
- extras/cinefiles/app/views/devise/registrations/new.html.erb
- extras/cinefiles/app/views/devise/sessions/new.html.erb
- extras/cinefiles/app/views/shared/_pdfs.html.erb
https://jira-secure.berkeley.edu/browse/HMP-352
> HMP-352: replaces <b> and <i> tags

- extras/pahma/app/assets/stylesheets/extras.scss
- portal/app/assets/stylesheets/shared.scss
https://jira-secure.berkeley.edu/browse/HMP-354
I also moved the custom focus ring styles to shared.scss.
> HMP-354: increases slideshow button color contrast 

- extras/bampfa/app/assets/stylesheets/extras.scss
- extras/bampfa/app/views/shared/_footer.html.erb
- extras/cinefiles/app/assets/stylesheets/extras.scss
- extras/cinefiles/app/views/shared/_footer.html.erb
https://jira-secure.berkeley.edu/browse/HMP-327
https://jira-secure.berkeley.edu/browse/HMP-339
> HMP-327, HMP-339: makes blacklight logo accessible

- extras/pahma/app/assets/stylesheets/extras.scss
- portal/app/assets/stylesheets/shared.scss
https://jira-secure.berkeley.edu/browse/HMP-341
> HMP-341: prevents caption overlap when text resized

- portal/app/assets/stylesheets/shared.scss
https://jira-secure.berkeley.edu/browse/HMP-344
> HMP-344: limits sidebar shrinkage

- extras/bampfa/config/locales/blacklight.en.yml
- extras/cinefiles/config/locales/blacklight.en.yml
- extras/common/config/locales/blacklight.en.yml
- extras/pahma/config/locales/blacklight.en.yml
https://jira-secure.berkeley.edu/browse/HMP-321
https://jira-secure.berkeley.edu/browse/HMP-323
> HMP-321, HMP-323: adjusts compact pagination text for screen readers

- extras/bampfa/config/locales/blacklight.en.yml
- extras/cinefiles/config/locales/blacklight.en.yml
- extras/common/config/locales/blacklight.en.yml
- extras/pahma/config/locales/blacklight.en.yml
https://jira-secure.berkeley.edu/browse/HMP-326
> HMP-326: adds context to view-type links

- extras/cinefiles/app/views/shared/_header_navbar.html.erb
- portal/app/assets/stylesheets/shared.scss
- portal/app/helpers/search_history_constraints_helper.rb
- portal/app/helpers/url_helper.rb
- portal/app/views/search_history/index.html.erb
https://jira-secure.berkeley.edu/browse/HMP-350
https://jira-secure.berkeley.edu/browse/HMP-351
> HMP-350, HMP-351: makes search history a list with no blank rows

- deploy.sh
https://jira-secure.berkeley.edu/browse/HMP-360
> HMP-360: updates deploy script to install, not update bundle

- extras/bampfa/app/assets/stylesheets/_variables.scss
- extras/cinefiles/app/assets/stylesheets/_variables.scss
- extras/cinefiles/app/assets/stylesheets/extras.scss
- portal/app/assets/stylesheets/shared.scss
https://jira-secure.berkeley.edu/browse/HMP-310
> HMP-310: increases primary color and search history label contrast

- extras/pahma/app/assets/stylesheets/extras.scss
- extras/pahma/app/views/catalog/_home_text.html.erb
https://jira-secure.berkeley.edu/browse/HMP-305
> HMP-305: provides alt text for pahma splash links

- extras/bampfa/app/controllers/catalog_controller.rb
- extras/bampfa/app/helpers/application_helper.rb
- extras/bampfa/app/presenters/blacklight/thumbnail_presenter.rb
- extras/bampfa/app/views/catalog/_show_default.html.erb
- extras/cinefiles/app/helpers/application_helper.rb
https://jira-secure.berkeley.edu/browse/HMP-313
Review with `w=1`
> HMP-313: adds alt text for BAMPFA thumbnails and catalog images

- extras/bampfa/app/views/shared/_footer.html.erb
- extras/cinefiles/app/views/shared/_footer.html.erb
- extras/pahma/app/views/shared/_footer.html.erb
https://jira-secure.berkeley.edu/browse/HMP-333
https://jira-secure.berkeley.edu/browse/HMP-338
> HMP-333, HMP-338: removes invalid nav role from footer links list

- extras/bampfa/app/assets/stylesheets/extras.scss
- extras/pahma/app/helpers/application_helper.rb
- extras/pahma/app/presenters/blacklight/thumbnail_presenter.rb
- portal/app/assets/stylesheets/shared.scss
https://jira-secure.berkeley.edu/browse/HMP-361
> HMP-361: suppresses description in restricted image alt text

- portal/app/helpers/render_constraints_helper.rb
- portal/app/helpers/search_history_constraints_helper.rb
https://jira-secure.berkeley.edu/browse/HMP-358
> HMP-358: dedupes advanced search constraint elements

- extras/bampfa/app/helpers/application_helper.rb
- extras/bampfa/app/presenters/blacklight/thumbnail_presenter.rb
- extras/cinefiles/app/helpers/application_helper.rb
- extras/cinefiles/app/presenters/blacklight/thumbnail_presenter.rb
- extras/pahma/app/helpers/application_helper.rb
https://jira-secure.berkeley.edu/browse/HMP-361
https://jira-secure.berkeley.edu/browse/HMP-363
> HMP-361, HMP-363: adjusts catalog image alt text, adds thumbnail alt text for Cinefiles

- extras/common/app/models/search_builder.rb
- extras/pahma/app/assets/stylesheets/extras.scss
- portal/app/assets/stylesheets/shared.scss
https://jira-secure.berkeley.edu/browse/HMP-364
> HMP-364: fixes spacing and alignment in advanced search

- portal/app/views/blacklight/nav/_search_history.html.erb
- portal/app/views/blacklight_advanced_search/_facet_limit.html.erb
https://jira-secure.berkeley.edu/browse/HMP-358
Also fixes Search History aria-label syntax.
> HMP-358: dedupes advanced search constraint elements in facet panels

- extras/bampfa/config/locales/blacklight.en.yml
- extras/cinefiles/config/locales/blacklight.en.yml
- extras/common/config/locales/blacklight.en.yml
- extras/pahma/config/locales/blacklight.en.yml
- portal/app/components/blacklight/constraint_layout_component.html.erb
- portal/app/components/blacklight/constraint_layout_component.rb
- portal/app/components/blacklight/facet_item_component.rb
https://jira-secure.berkeley.edu/browse/HMP-349
> HMP-349: removes invalid title, adds context to constraint filter links

- extras/bampfa/app/assets/stylesheets/extras.scss
- extras/bampfa/app/views/shared/_footer.html.erb
- extras/cinefiles/app/assets/stylesheets/extras.scss
- extras/cinefiles/app/views/shared/_footer.html.erb
- extras/pahma/app/views/shared/_footer.html.erb
- portal/app/assets/stylesheets/shared.scss
https://jira-secure.berkeley.edu/browse/HMP-371
I also fixed some "problematic alt text" errors from ARC Toolkit.
> HMP-371: darkens masonry caption background; improves focus outlines

- portal/app/components/search_bar_component.html.erb
- portal/app/components/search_bar_component.rb
- portal/app/views/layouts/blacklight/base.html.erb
https://jira-secure.berkeley.edu/browse/HMP-372
> HMP-372: fixes search operator label, duplicate IDs

- portal/app/helpers/search_history_constraints_helper.rb
- portal/app/helpers/url_helper.rb
https://jira-secure.berkeley.edu/browse/HMP-350
> HMP-350: removes search history aria-desc, adjusts cols

- portal/app/views/layouts/application.html.erb
- portal/app/views/layouts/mailer.html.erb
- portal/public/404.html
- portal/public/422.html
- portal/public/500.html
https://jira-secure.berkeley.edu/browse/HMP-355
> HMP-355: adds missing lang attr in static html

- portal/app/assets/javascripts/blacklight_gallery.js
- portal/app/assets/stylesheets/shared.scss
https://jira-secure.berkeley.edu/browse/HMP-359
> HMP-359: improves aria, color contrast in slideshow modal

- extras/bampfa/app/helpers/application_helper.rb
- extras/cinefiles/app/helpers/application_helper.rb
- extras/pahma/app/helpers/application_helper.rb
- portal/app/assets/stylesheets/shared.scss
https://jira-secure.berkeley.edu/browse/HMP-367
> HMP-367: adds alt text, visible focus to 3D renderings

- extras/bampfa/app/helpers/application_helper.rb
- extras/bampfa/config/locales/blacklight.en.yml
- extras/cinefiles/app/helpers/application_helper.rb
- extras/cinefiles/config/locales/blacklight.en.yml
- extras/common/app/helpers/application_helper.rb
- extras/common/config/locales/blacklight.en.yml
- extras/pahma/app/helpers/application_helper.rb
- extras/pahma/app/presenters/thumbnail_presenter.rb
- extras/pahma/config/locales/blacklight.en.yml
- portal/app/assets/stylesheets/shared.scss
- portal/app/components/document/bookmark_component.html.erb
- portal/app/components/document/bookmark_component.rb
- portal/app/helpers/catalog_helper.rb
- portal/app/helpers/component_helper.rb
- portal/app/views/catalog/_bookmark_control.html.erb
- portal/app/views/catalog/_index_header.html.erb
- portal/app/views/catalog/_show_tools.html.erb
https://jira-secure.berkeley.edu/browse/HMP-322
> HMP-322: adds context to bookmark labels for screen reader

- extras/common/app/helpers/blacklight_advanced_search/advanced_helper_behavior.rb
https://jira-secure.berkeley.edu/browse/HMP-375
> HMP-375: corrects label ref on advanced search operator

- extras/bampfa/app/helpers/application_helper.rb
- extras/cinefiles/app/helpers/application_helper.rb
- extras/common/app/helpers/application_helper.rb
- extras/pahma/app/helpers/application_helper.rb
https://jira-secure.berkeley.edu/browse/HMP-378
> HMP-378: increases color contrast for red 'deaccessioned'

- install_ucb.sh
https://jira-secure.berkeley.edu/browse/HMP-374
> HMP-374: updates install_ucb script w a11y customizations

- portal/app/views/layouts/blacklight/bampfa_base_CS-9131.html.erb
- portal/app/views/layouts/blacklight/base.html.erb
- portal/app/views/layouts/blacklight/cinefiles_base_CS-9131.html.erb
- portal/app/views/layouts/blacklight/pahma_base_CS-9131.html.erb
https://jira-secure.berkeley.edu/browse/HMP-380
> [HMP-380] add siteimprove scripts

- portal/app/views/layouts/blacklight/bampfa_base_CS-9131.html.erb
- portal/app/views/layouts/blacklight/base.html.erb
- portal/app/views/layouts/blacklight/cinefiles_base_CS-9131.html.erb
- portal/app/views/layouts/blacklight/pahma_base_CS-9131.html.erb
https://jira-secure.berkeley.edu/browse/HMP-380
> [HMP-380] replace double quote with single quote

- extras/bampfa/app/assets/stylesheets/extras.scss
- extras/bampfa/app/helpers/application_helper.rb
- extras/bampfa/app/views/catalog/_home_text.html.erb
- extras/bampfa/app/views/shared/_footer.html.erb
- extras/cinefiles/app/views/devise/registrations/new.html.erb
- extras/cinefiles/app/views/devise/sessions/new.html.erb
- extras/cinefiles/app/views/shared/_pdfs.html.erb
- portal/app/assets/stylesheets/shared.scss
- portal/app/components/blacklight/system/modal_component.html.erb
- portal/app/views/blacklight_range_limit/range_segments.html.erb
https://jira-secure.berkeley.edu/browse/HMP-381
> HMP-381: fixes a11y best practice issues in bampfa

- portal/app/assets/stylesheets/shared.scss
- portal/app/components/blacklight_range_limit/range_form_component.rb
- portal/app/helpers/catalog_helper.rb
https://jira-secure.berkeley.edu/browse/HMP-382
Plus a couple other fixes.
> HMP-382: strips html from page title

- extras/common/app/assets/stylesheets/shared.scss
https://jira-secure.berkeley.edu/browse/HMP-388
> HMP-388: straightens focus ring on documents list

- extras/bampfa/app/views/shared/_footer.html.erb
- extras/cinefiles/app/views/shared/_footer.html.erb
- extras/pahma/app/views/shared/_footer.html.erb
https://jira-secure.berkeley.edu/browse/HMP-389
> HMP-389: Updates accessibility link URL

- extras/bampfa/app/helpers/application_helper.rb
- extras/pahma/app/assets/stylesheets/extras.scss
- extras/pahma/app/views/catalog/_home_text.html.erb
https://jira-secure.berkeley.edu/browse/HMP-392
> HMP-392: fixes error on bampfa 'load more'; updates pahma splash text

- extras/bampfa/app/views/shared/_header_navbar.html.erb
- extras/cinefiles/app/assets/stylesheets/extras.scss
- extras/cinefiles/app/views/shared/_header_navbar.html.erb
- extras/common/app/assets/stylesheets/shared.scss
- extras/common/app/views/layouts/blacklight/bampfa_base_CS-9131.html.erb
- extras/common/app/views/layouts/blacklight/base.html.erb
- extras/common/app/views/layouts/blacklight/cinefiles_base_CS-9131.html.erb
- extras/common/app/views/layouts/blacklight/pahma_base_CS-9131.html.erb
- extras/pahma/app/views/shared/_header_navbar.html.erb
https://jira-secure.berkeley.edu/browse/HMP-399
> HMP-399: improves focus ring on main content

- extras/bampfa/app/views/shared/_header_navbar.html.erb
- extras/cinefiles/app/views/shared/_header_navbar.html.erb
- extras/pahma/app/views/shared/_header_navbar.html.erb
https://jira-secure.berkeley.edu/browse/HMP-407
> HMP-407: shortens alt text, adds same page indicator to home link

- extras/bampfa/app/controllers/catalog_controller.rb
- extras/cinefiles/app/assets/stylesheets/extras.scss
- extras/cinefiles/app/components/blacklight/facet_field_list_component.html.erb
- extras/cinefiles/app/controllers/catalog_controller.rb
- extras/common/app/assets/stylesheets/shared.scss
- extras/common/app/components/blacklight/facet_field_inclusive_constraint_component.html.erb
- extras/common/app/components/blacklight/facet_field_inclusive_constraint_component.rb
- extras/common/app/controllers/catalog_controller.rb
- extras/pahma/app/assets/stylesheets/extras.scss
- extras/pahma/app/components/blacklight/facet_field_list_component.html.erb
- extras/pahma/app/controllers/catalog_controller.rb
https://jira-secure.berkeley.edu/browse/HMP-405
> HMP-405: differentiates inclusive from exclusive facet filters

- extras/cinefiles/app/assets/stylesheets/tiles.css
- extras/cinefiles/app/views/catalog/_home_text.html.erb
https://jira-secure.berkeley.edu/browse/HMP-400
> HMP-400: makes flip cards respond to focus; increases font size

- extras/cinefiles/app/views/devise/registrations/edit.html.erb
- extras/pahma/app/views/devise/registrations/edit.html.erb
https://jira-secure.berkeley.edu/browse/HMP-419
> HMP-419: clarifies 'cancel account' language

- extras/common/app/views/layouts/blacklight/bampfa_base_CS-9131.html.erb
- extras/common/app/views/layouts/blacklight/cinefiles_base_CS-9131.html.erb
- extras/common/app/views/layouts/blacklight/pahma_base_CS-9131.html.erb
- extras/pahma/app/helpers/application_helper.rb
- extras/pahma/app/views/shared/_user_util_links.html.erb
https://jira-secure.berkeley.edu/browse/HMP-410
> HMP-410: indicates permalinks and external links

- extras/common/app/views/layouts/blacklight.html.erb
https://jira-secure.berkeley.edu/browse/HMP-396
> HMP-396: swaps tab order of sidebar and main content

- extras/bampfa/app/views/catalog/_show_default.html.erb
- extras/bampfa/app/views/catalog/_show_preview.html.erb
- extras/bampfa/app/views/layouts/blacklight/base.html.erb
- extras/bampfa/config/routes.rb
https://jira-secure.berkeley.edu/browse/HMP-423
> HMP-423: moves bampfa artist preview after bookmark checkbox

- extras/bampfa/app/controllers/application_controller.rb
- extras/bampfa/app/helpers/url_helper.rb
- extras/cinefiles/app/controllers/application_controller.rb
- extras/cinefiles/app/helpers/url_helper.rb
- extras/common/app/assets/stylesheets/shared.scss
- extras/common/app/components/blacklight/constraint_layout_component.html.erb
- extras/common/app/components/blacklight/facet_item_component.rb
- extras/common/app/components/blacklight/system/dropdown_component.html.erb
- extras/common/app/components/blacklight/system/dropdown_component.rb
- extras/common/app/components/blacklight/system/flash_message_component.html.erb
- extras/common/app/components/blacklight/system/flash_message_component.rb
- extras/common/app/controllers/application_controller.rb
- extras/common/app/views/shared/_flash_messages.html.erb
- extras/common/app/views/shared/_flash_msg.html.erb
- extras/pahma/app/controllers/application_controller.rb
- extras/pahma/app/helpers/url_helper.rb
https://jira-secure.berkeley.edu/browse/HMP-414
> HMP-414: adds screen reader alert for facet, sort, and pagination changes

- extras/bampfa/app/controllers/application_controller.rb
- extras/bampfa/app/helpers/url_helper.rb
- extras/cinefiles/app/controllers/application_controller.rb
- extras/cinefiles/app/helpers/url_helper.rb
- extras/common/app/controllers/application_controller.rb
- extras/pahma/app/controllers/application_controller.rb
- extras/pahma/app/helpers/url_helper.rb
https://jira-secure.berkeley.edu/browse/HMP-414
> HMP-414: fixes handling of screen reader alert query param

- extras/bampfa/app/controllers/application_controller.rb
- extras/bampfa/app/helpers/url_helper.rb
- extras/cinefiles/app/controllers/application_controller.rb
- extras/cinefiles/app/helpers/url_helper.rb
- extras/common/app/assets/javascripts/focus.js
- extras/common/app/assets/stylesheets/shared.scss
- extras/common/app/components/blacklight/constraint_component.html.erb
- extras/common/app/components/blacklight/constraint_component.rb
- extras/common/app/components/blacklight/constraint_layout_component.html.erb
- extras/common/app/components/blacklight/constraint_layout_component.rb
- extras/common/app/components/blacklight/facet_item_component.rb
- extras/common/app/components/blacklight/response/facet_group_component.html.erb
- extras/common/app/components/blacklight/response/facet_group_component.rb
- extras/common/app/components/blacklight/system/dropdown_component.rb
- extras/common/app/controllers/application_controller.rb
- extras/common/app/helpers/render_constraints_helper.rb
- extras/common/app/views/catalog/_constraints_element.html.erb
- extras/common/app/views/layouts/blacklight/bampfa_base_CS-9131.html.erb
- extras/common/app/views/layouts/blacklight/base.html.erb
- extras/common/app/views/layouts/blacklight/cinefiles_base_CS-9131.html.erb
- extras/common/app/views/layouts/blacklight/pahma_base_CS-9131.html.erb
- extras/common/app/views/shared/_focus_mgmt.html.erb
- extras/pahma/app/controllers/application_controller.rb
- extras/pahma/app/helpers/url_helper.rb
https://jira-secure.berkeley.edu/browse/HMP-414
> HMP-414: manages focus after constraint, sort, and page size changes
